// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_key_from_seed`

/// Encrypts data using AES-256-GCM with seed phrase
Uint8List encryptNetworkData({
  required String data,
  required String seedPhrase,
}) => RustLib.instance.api.crateApiCryptoEncryptNetworkData(
  data: data,
  seedPhrase: seedPhrase,
);

/// Decrypts data using AES-256-GCM with seed phrase
String decryptNetworkData({
  required List<int> encryptedData,
  required String seedPhrase,
}) => RustLib.instance.api.crateApiCryptoDecryptNetworkData(
  encryptedData: encryptedData,
  seedPhrase: seedPhrase,
);
