// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a new 24-word BIP39 seed phrase for cryptographic identity
String generateSeedPhrase() =>
    RustLib.instance.api.crateApiIdentityGenerateSeedPhrase();

/// Validates a seed phrase
bool validateSeedPhrase({required String phrase}) =>
    RustLib.instance.api.crateApiIdentityValidateSeedPhrase(phrase: phrase);

/// Derives a deterministic seed from the mnemonic phrase
/// This can be used for key derivation
Uint8List deriveSeedFromPhrase({required String phrase, String? passphrase}) =>
    RustLib.instance.api.crateApiIdentityDeriveSeedFromPhrase(
      phrase: phrase,
      passphrase: passphrase,
    );
