// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_broadcast_address`, `calculate_network_prefix`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Gets the local IPv4 address of the device
String? getLocalIpv4Address() =>
    RustLib.instance.api.crateApiNetworkGetLocalIpv4Address();

/// Gets the local IPv6 address of the device
String? getLocalIpv6Address() =>
    RustLib.instance.api.crateApiNetworkGetLocalIpv6Address();

/// Gets the public IPv4 address by querying external services
String? getPublicIpv4Address() =>
    RustLib.instance.api.crateApiNetworkGetPublicIpv4Address();

/// Gets the public IPv6 address by querying external services
String? getPublicIpv6Address() =>
    RustLib.instance.api.crateApiNetworkGetPublicIpv6Address();

/// Gets all network information (local and public IPs with LAN details)
NetworkInfo getNetworkInfo() =>
    RustLib.instance.api.crateApiNetworkGetNetworkInfo();

/// Check if two IP addresses are on the same subnet
bool areOnSameSubnet({
  required String ip1,
  required String ip2,
  required String subnetMask,
}) => RustLib.instance.api.crateApiNetworkAreOnSameSubnet(
  ip1: ip1,
  ip2: ip2,
  subnetMask: subnetMask,
);

class NetworkInfo {
  final String? localIpv4;
  final String? localIpv6;
  final String? publicIpv4;
  final String? publicIpv6;
  final String? subnetMask;
  final String? gateway;
  final String? networkPrefix;
  final String? interfaceName;
  final String? macAddress;
  final String? broadcastAddress;

  const NetworkInfo({
    this.localIpv4,
    this.localIpv6,
    this.publicIpv4,
    this.publicIpv6,
    this.subnetMask,
    this.gateway,
    this.networkPrefix,
    this.interfaceName,
    this.macAddress,
    this.broadcastAddress,
  });

  @override
  int get hashCode =>
      localIpv4.hashCode ^
      localIpv6.hashCode ^
      publicIpv4.hashCode ^
      publicIpv6.hashCode ^
      subnetMask.hashCode ^
      gateway.hashCode ^
      networkPrefix.hashCode ^
      interfaceName.hashCode ^
      macAddress.hashCode ^
      broadcastAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInfo &&
          runtimeType == other.runtimeType &&
          localIpv4 == other.localIpv4 &&
          localIpv6 == other.localIpv6 &&
          publicIpv4 == other.publicIpv4 &&
          publicIpv6 == other.publicIpv6 &&
          subnetMask == other.subnetMask &&
          gateway == other.gateway &&
          networkPrefix == other.networkPrefix &&
          interfaceName == other.interfaceName &&
          macAddress == other.macAddress &&
          broadcastAddress == other.broadcastAddress;
}
